import type { TeamMember } from "./types";

export const TEAM: TeamMember[] = [
  {
    id: "amy",
    name: "Amy",
    role: "Student Success Lead",
    responsibilities: "Onboarding, your first 72 hours, scheduling, escalations.",
    helpsWith: ["Onboarding questions", "Scheduling", "Where to find things"],
    contact: "Slack DM @amy",
    initials: "A",
    color: "from-pink-500/30 to-pink-700/10",
  },
  {
    id: "irma",
    name: "Irma",
    role: "Operations & Billing",
    responsibilities: "Account access, billing, subscription, paperwork.",
    helpsWith: ["Login issues", "Billing", "Invoices"],
    contact: "Slack DM @irma",
    initials: "I",
    color: "from-amber-500/30 to-amber-700/10",
  },
  {
    id: "tyler",
    name: "Tyler",
    role: "Senior Trading Coach",
    responsibilities: "Strategy reviews, trade analysis, prop firm guidance.",
    helpsWith: ["Trade reviews", "Prop firm rules", "Bot performance"],
    contact: "Slack #ask-a-coach",
    initials: "T",
    color: "from-brand/30 to-brand-subtle/10",
  },
  {
    id: "dan",
    name: "Dan",
    role: "Technical Support",
    responsibilities: "VPS, NinjaTrader, BoxSeats deployment.",
    helpsWith: ["VPS setup", "NinjaTrader errors", "Bot deployment"],
    contact: "Slack #tech-support",
    initials: "D",
    color: "from-emerald-500/30 to-emerald-700/10",
  },
  {
    id: "jenn",
    name: "Jenn",
    role: "Community Manager",
    responsibilities: "Slack, Zoom calls, weekly office hours.",
    helpsWith: ["Slack invites", "Zoom links", "Replays"],
    contact: "Slack DM @jenn",
    initials: "J",
    color: "from-purple-500/30 to-purple-700/10",
  },
];
